<?php

declare(strict_types=1);

namespace HiEvents\Assistant\Domain\Tools;

use HiEvents\Assistant\Domain\AssistantContext;
use HiEvents\DomainObjects\Enums\ProductType;
use HiEvents\DomainObjects\ProductDomainObject;
use HiEvents\DomainObjects\SeatingSectionDomainObject;
use HiEvents\DomainObjects\Status\EventStatus;
use HiEvents\DomainObjects\Status\SeatingSectionStatus;
use HiEvents\Http\DTO\QueryParamsDTO;
use HiEvents\Repository\Interfaces\EventRepositoryInterface;
use HiEvents\Repository\Interfaces\ProductRepositoryInterface;
use HiEvents\Repository\Interfaces\SeatingSectionRepositoryInterface;
use HiEvents\Services\Application\Handlers\SeatingSection\CreateSeatingSectionHandler;
use HiEvents\Services\Application\Handlers\SeatingSection\DTO\UpsertSeatingSectionDTO;
use HiEvents\Services\Domain\Product\Exception\UnrecognizedProductIdException;
use HiEvents\Services\Domain\Seating\CreateSeatingSectionService;
use HiEvents\Services\Domain\Seating\Exception\InvalidSeatingLayoutException;
use HiEvents\Services\Infrastructure\Authorization\IsAuthorizedService;
use Prism\Prism\Schema\NumberSchema;
use Psr\Log\LoggerInterface;

/**
 * "Una platea de 20 filas de 30": one section of the seat map, sector by
 * sector, the same way the panel's seating designer builds it. Each section
 * sells through one ticket type; the seats are generated by the core service
 * and the public page draws the map as soon as a section exists.
 */
class CreateSeatingSectionTool extends AbstractAssistantWriteTool
{
    public function __construct(
        AssistantContext                                    $context,
        IsAuthorizedService                                 $isAuthorizedService,
        EventRepositoryInterface                            $events,
        LoggerInterface                                     $logger,
        private readonly ProductRepositoryInterface         $products,
        private readonly SeatingSectionRepositoryInterface  $sections,
        private readonly CreateSeatingSectionHandler        $createSection,
    )
    {
        parent::__construct($context, $isAuthorizedService, $events, $logger);
    }

    protected function configure(): void
    {
        $this
            ->as('create_seating_section')
            ->for('Adds one section (sector) to the event seat map: a grid of rows x seats per row sold '
                . 'through one ticket type, e.g. "Platea, 20 rows of 30, ticket Platea". Build the room one '
                . 'section at a time (Platea, Pullman, VIP...). Max 100 rows, 100 seats per row, 2000 seats '
                . 'per section. Ask for the ticket first (create_ticket) if it does not exist. Preview '
                . 'without confirm; confirm=true creates it; MODIFICAR on a published event.')
            ->withNumberParameter('event_id', 'The event.')
            ->withStringParameter('name', 'Section name as the buyer sees it: "Platea", "Pullman", "Campo".')
            ->withNumberParameter('ticket_id', 'The ticket type (product_id) sold in this section. From get_event_stats or create_ticket.')
            ->withNumberParameter('rows', 'Number of rows (1-100).')
            ->withNumberParameter('seats_per_row', 'Seats in each row (1-100).')
            ->withArrayParameter('aisles_after_seats', 'Optional: seat numbers after which there is an aisle, e.g. [10, 20] for a 30-seat row split in three.', new NumberSchema('seat', 'seat number'), required: false)
            ->withBooleanParameter('confirm', 'Pass true only after the organizer confirmed the preview.', required: false)
            ->withStringParameter('confirmation_phrase', 'The exact word MODIFICAR typed by the organizer, only for published events.', required: false);
    }

    public function __invoke(
        int|float  $event_id,
        string     $name,
        int|float  $ticket_id,
        int|float  $rows,
        int|float  $seats_per_row,
        ?array     $aisles_after_seats = null,
        ?bool      $confirm = null,
        ?string    $confirmation_phrase = null,
    ): string
    {
        $args = $this->validateArguments(
            compact('event_id', 'name', 'ticket_id', 'rows', 'seats_per_row', 'aisles_after_seats'),
            [
                'event_id' => 'required|integer|min:1',
                'name' => 'required|string|min:1|max:100',
                'ticket_id' => 'required|integer|min:1',
                'rows' => 'required|integer|min:1|max:' . CreateSeatingSectionService::MAX_ROWS,
                'seats_per_row' => 'required|integer|min:1|max:' . CreateSeatingSectionService::MAX_SEATS_PER_ROW,
                'aisles_after_seats' => 'nullable|array|max:10',
                'aisles_after_seats.*' => 'integer|min:1',
            ],
        );

        $event = $this->authorizeEvent((int)$args['event_id']);
        $isLive = $event->getStatus() === EventStatus::LIVE->name;
        $seats = (int)$args['rows'] * (int)$args['seats_per_row'];

        if ($seats > CreateSeatingSectionService::MAX_SEATS_PER_SECTION) {
            return $this->toJson(['error' => 'invalid_arguments', 'details' => sprintf('A section holds at most %d seats; split it in two.', CreateSeatingSectionService::MAX_SEATS_PER_SECTION)]);
        }

        /** @var ProductDomainObject|null $ticket */
        $ticket = $this->products->findFirstWhere(['id' => (int)$args['ticket_id'], 'event_id' => $event->getId()]);

        if ($ticket === null || $ticket->getProductType() !== ProductType::TICKET->name) {
            return $this->toJson(['error' => 'ticket_not_found', 'details' => 'No ticket type with that id on this event. Use get_event_stats for the ids, or create it first.']);
        }

        $existing = $this->sections->findByEventId($event->getId(), new QueryParamsDTO(per_page: 100))->items();
        $sameName = collect($existing)->first(fn(SeatingSectionDomainObject $s): bool => mb_strtolower($s->getName()) === mb_strtolower($args['name']));

        if ($sameName !== null) {
            return $this->toJson([
                'status' => 'already_exists',
                'section' => $this->describe($sameName),
                'hint' => 'A section with this name already exists on the event - most likely created earlier in this conversation. Nothing was created.',
            ]);
        }

        $payload = [
            'event_id' => $event->getId(),
            'event_title' => $this->clip($event->getTitle()),
            'event_status' => $event->getStatus(),
            'name' => $args['name'],
            'ticket' => ['id' => $ticket->getId(), 'title' => $this->clip($ticket->getTitle())],
            'rows' => (int)$args['rows'],
            'seats_per_row' => (int)$args['seats_per_row'],
            'total_seats' => $seats,
            'aisles_after_seats' => $args['aisles_after_seats'] ?? [],
            'existing_sections' => array_map(fn(SeatingSectionDomainObject $s): array => $this->describe($s), $existing),
        ];

        if ($confirm !== true) {
            return $this->toJson([
                'status' => 'needs_confirmation',
                'would_create' => $payload,
                'hint' => $isLive
                    ? 'This event is published: show the section (rows x seats, ticket) and ask the organizer to reply with the exact word MODIFICAR before calling again with confirm=true and confirmation_phrase.'
                    : 'Describe the section in words (rows, seats per row, total, which ticket) and ask for confirmation; call again with confirm=true once they agree. Then ask if the room has another sector.',
            ]);
        }

        if (($refusal = $this->doubleCheck($isLive, $confirm, $confirmation_phrase, 'MODIFICAR')) !== null) {
            return $refusal;
        }

        try {
            $section = $this->createSection->handle(UpsertSeatingSectionDTO::from([
                'name' => $args['name'],
                'event_id' => $event->getId(),
                'product_id' => $ticket->getId(),
                'row_count' => (int)$args['rows'],
                'seats_per_row' => (int)$args['seats_per_row'],
                'status' => SeatingSectionStatus::ACTIVE->name,
                'disabled_seats' => null,
                'aisle_positions' => $args['aisles_after_seats'] ?: null,
            ]));
        } catch (UnrecognizedProductIdException|InvalidSeatingLayoutException $e) {
            return $this->toJson(['error' => 'invalid_arguments', 'details' => $e->getMessage()]);
        }

        $this->logWrite('seating_section_created', ['event_id' => $event->getId(), 'section_id' => $section->getId(), 'seats' => $seats]);

        return $this->toJson([
            'status' => 'created',
            'section' => $this->describe($section),
            'total_sections' => count($existing) + 1,
            'next_steps' => 'The seat map now shows this section. Ask whether the room has another sector; when done, remind them buyers pick their seat at checkout.',
        ]);
    }

    private function describe(SeatingSectionDomainObject $section): array
    {
        return [
            'id' => $section->getId(),
            'name' => $this->clip($section->getName()),
            'ticket_id' => $section->getProductId(),
            'rows' => $section->getRowCount(),
            'seats_per_row' => $section->getSeatsPerRow(),
            'total_seats' => $section->getRowCount() * $section->getSeatsPerRow(),
            'status' => $section->getStatus(),
        ];
    }
}
